- name: lookup secretsmanager secret in the current region
  hosts: local
  connection: local
  tasks:
- name: print Roboshop root password
  debug:
    msg: Root password ="{{ lookup('amazon.aws.aws_secret', 'roboshop/mysql_root_password', region=us-east-1) }}"
