[local]
localhost

[frontend]
nmarriaws.xyz

[mongodb]
mongodb.nmarriaws.xyz

[redis]
redis.nmarriaws.xyz

[mysql]
mysql.nmarriaws.xyz

[rabbitmq]
rabbitmq.nmarriaws.xyz

[catalogue]
catalogue.nmarriaws.xyz

[user]
user.nmarriaws.xyz

[cart]
cart.nmarriaws.xyz

[shipping]
shipping.nmarriaws.xyz

[payment]
payment.nmarriaws.xyz