 - name: get the password from AWS Secret Manager
   debug:
    msg: "{{ lookup('amazon.aws.aws_ssm', '/roboshop/mysql/password', region='us-east-1') from json }}"
 - name: install mysql server
   package:
      name: mysql-server
      state: present
 - name: enable and start mysql server
   service:
      name: mysqld
      state: started
      enabled: yes
 - name: set root password
   command: mysql_secure_installation --set-root-pass "{{ mysql_root_password }}""