ansible_user: ec2-user
ansible_password: DevOps321
mysql_root_password: RoboShop@1
MONGODB_HOST: mongodb.nmarriaws.xyz
REDIS_HOST: redis.nmarriaws.xyz
CATALOGUE_HOST: catalogue.nmarriaws.xyz
CART_HOST: cart.nmarriaws.xyz
SHIPPING_HOST: shipping.nmarriaws.xyz
MYSQL_HOST: mysql.nmarriaws.xyz
USER_HOST: user.nmarriaws.xyz
PAYMENT_HOST: payment.nmarriaws.xyz
RABBITMQ_HOST: rabbitmq.nmarriaws.xyz